### ISSUE TITLE
Cyrillic names in lists are broken.

### ISSUE THREAD

**Issue by phtmgt** [Mailtrain-org/mailtrain#629] opened 2019-07-04 14:22 UTC
When subscriber lists contain cyrillic characters, they are scrambled in the e-mail body. The funny thing is they appear fine when looking at inbox (both web gmail and app)

List:
<img width="422" alt="Screenshot 2019-07-04 at 17 18 49" src="https://user-images.githubusercontent.com/14073311/60673192-e87c3480-9e7f-11e9-9b7f-bb11f430f7fb.png">

Email body:
<img width="352" alt="Screenshot 2019-07-04 at 17 20 59" src="https://user-images.githubusercontent.com/14073311/60673321-22e5d180-9e80-11e9-84ca-3b9a1a56e78e.png">

Funny thing is the rest of the text (also cyrillic) appears fine.

Inbox view:
<img width="367" alt="Screenshot 2019-07-04 at 17 22 07" src="https://user-images.githubusercontent.com/14073311/60673398-4b6dcb80-9e80-11e9-856c-1d22b7891288.png">

Something wrong with the database maybe?

Any suggestions are appreciated.

The issue is not gmail, as the e-mail was forwarded to hotmail just in case.

**Comment by bures** [comment] 2019-07-04 14:52
Is it Mailtrain v1 or v2 beta?

**Comment by plamenh** [comment] 2019-07-04 15:21
V1. Probably a duplicate of https://github.com/Mailtrain-org/mailtrain/issues/598

**Comment by D4rk4** [comment] 2020-09-16 14:21
Same in V2

**Comment by forgeOneHQ** [comment] 2024-03-16 08:50
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.

**Closed by forgeOneHQ** 2024-03-16 08:50 UTC
