### ISSUE TITLE
Error sending campaing when merge tag is a number

### ISSUE THREAD

**Issue by ganeshkrishnan1** [Mailtrain-org/mailtrain#1018] opened 2021-03-01 04:31 UTC
I created a new Field with Integer value [MERGE_MONTH]

If I use this field in the email template, it fails with value.replace is not a function.

I tried to debug this a bit and it looks like it fails at this place
`
 let searchVal = '%' + params.search.value.replace(/\\/g, '\\\\').replace(/([%_])/g, '\\$1') + '%';`

here params.search.value doesnt seem to be a string and hence there is no replace function to it.

**Comment by bures** [comment] 2021-05-26 05:23
Is this v1 or v2? If it's v2, could you post exact steps how to replicate the issue, a screenshot and the exact file and line number where it fails? Thanks.

**Comment by ganeshkrishnan1** [comment] 2021-05-29 19:20
It's version 2. The exact bug is in the line above: when params.search.value is integer it doesnt have replace function (like string does)

replicate by creating a number tag and then using it in a template.

**Comment by davidwindell** [comment] 2022-05-10 13:35
Same here, seems a duplicate of #809

**Comment by forgeOneHQ** [comment] 2024-03-16 09:12
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.

**Closed by forgeOneHQ** 2024-03-16 09:12 UTC

**Comment by ganeshkrishnan1** [comment] 2024-03-16 16:58
If you have modules/tasks that needs help you can create tickets and I can put some of our team members to volunteer time
