### ISSUE TITLE
Mailtrain v2: custom field name is too long but working in v1

### ISSUE THREAD

**Issue by PhilippeAccorsi** [Mailtrain-org/mailtrain#639] opened 2019-07-23 08:03 UTC
## At present

In v1 I have one custom field with this name `Influenceur réseaux sociaux` merge tag is like this `MERGE_INFLUENCEUR_RESEAUX_SOCIAUX`.
When I tried to create same custom field in v2 this error appear:
~~~
alter table `subscription__3` add index `subscription__3_custom_influenceur_reseaux_sociaux_fnc7tpgmw_index`(`custom_influenceur_reseaux_sociaux_fnc7tpgmw`) - ER_TOO_LONG_IDENT: Identifier name 'subscription__3_custom_influenceur_reseaux_sociaux_fnc7tpgmw_index' is too long
~~~

## Expected

- [ ] Its possible to create custom field with same name (number of characters)

**Comment by Charlo270398** [comment] 2019-07-24 06:58
I tried to update a custom field with the same merge tag and it was OK, so I guess the problem is limited to custom fields _create function.

**Comment by Charlo270398** [comment] 2019-07-24 08:01
The error is located in _server/models/fields.js_ ; lines 559 to 564, but I really don't know how fix it.

**Comment by bures** [comment] 2019-07-24 08:04
We will have to change the mechanism how we generate the column names. If I did it correctly, it should be pretty much enough to change it at one place. We will also have to make a migration that renames columns in the DB. I'll take care of it, once I'm finished with merging the previous PRs. Thanks.

**Comment by bures** [comment] 2019-07-29 07:32
Should be fixed. Please try. If it doesn't work, reopen this issue. Thanks.

**Closed by bures** 2019-07-29 07:32 UTC
