### ISSUE TITLE
CATION: Cannot stop compaign on v2!

### ISSUE THREAD

**Issue by shahzaibcb** [Mailtrain-org/mailtrain#583] opened 2019-04-18 09:49 UTC
We're in really a big problem, we've triggered a campaign but mistakenly sent wrong template, now we're trying to stop campaign by clicking on stop button and it gives 500 internal error with message in response.

http://prntscr.com/ndluz8

**Comment by bures** [comment] 2019-04-18 10:43
Closing as duplicate of #582

**Closed by bures** 2019-04-18 10:43 UTC
