### ISSUE TITLE
API Feature Requests

### ISSUE THREAD

**Issue by alpha1** [Mailtrain-org/mailtrain#181] opened 2017-03-19 23:35 UTC
A couple items I'd like to see added to the API for mailtrain. I'd be happy to help anyway I can.
- get all lists
- get list custom fields and value options
- get all lists for subscriber/email

I'm working on a Gravity Forms Feed Addon which would require a lot of this to be able to work with custom fields, or editing subscriptions. I'm not much of a JS programmer, but I'll take a look and see if I can't help implement these.

**Comment by andris9** [comment] 2017-03-20 07:53
This is not planned, if you want to build it yourself, it would be great. All API calls are handled [here](https://github.com/andris9/mailtrain/blob/master/routes/api.js)

**Comment by jdfx** [comment] 2017-05-28 20:15
I will look at adding some of this functionality

I need to be able to:

- Create a list
- Create a campaign
- Get all custom fields on a list
- Manage segments somehow

**Comment by jdfx** [comment] 2017-05-29 20:08
Ok so I've begun by integrating Swagger that sits on the url /api-docs. I've also added a new end-point that just returns all the lists in the API.

Next is to finish documenting all of the current API end-points then I'll start creating more new ones.

My primary need is to create a campaign.

I'll also be adding some kind of mapping to templates, some kind of tags so that I can select the correct template to use when creating the campaign. This will also require an end-point that can list all the templates.

**Comment by jdfx** [comment] 2017-05-30 18:33
- [x ] Integrate Swagger on /api-docs
- [ ] Finish documenting API and providing working examples via Swagger-UI
- [x ] Add end-point to get all lists
- [ ] Add end-point to get all templates
- [ ] Add end-point to create a campaign
- [ ] Add tags to templates
- [ ] Add end-point to get custom fields and value options for a list
- [ ] Add end-point to get all lists for a particular subscriber (email)

**Comment by jdfx** [comment] 2017-05-31 23:21
Having an issue on line 505 of lib/models/campaigns.js

I have the API-endpoint successfully creating a campaign (it appears in the database and all is well):

```
router.post('/campaign', (req, res) => {
    campaigns.create(req.body, (err, id) => {
        if (err || !id) {
            log.error('API', err);
            res.status(500);
            return res.json({
                error: err.message || err,
                data: []
            });
        }
        res.status(200);
        res.json({
            data: {
                id
            }
        });
    });
});
```

However the server bombs out afterwards, complaining 'next' not being a function.

This is the section:

```
                        createCampaignTables(campaignId, err => {
                            if (err) {
                                // FIXME: rollback
                                return next(err);
                            }
                            return next(null, campaignId); // this line
                        });
```

'next' is the parameter passed to:

```
let create = next => {
// do stuff
}
```

**Comment by witzig** [comment] 2017-06-01 01:36
You're calling `campaign.create` with 2 params, but it takes 3:

```
module.exports.create = (campaign, opts, callback) => {
    ...
};
```

**Comment by jdfx** [comment] 2017-06-01 08:34
@witzig ... Thanks man - I drop 70 IQ points after 23:00.

**Comment by witzig** [comment] 2017-06-01 11:37
> [ ] Make get lists and create list return the actual listID shown in the UI. Currently returns DB index.

The DB index is the actual listID. The number shown in the UI is misleading.

> [ ] Add tags to templates

It would probably make sense to wait with this until @bures is done with the Namespace/ORM/React implementation. See [here](https://github.com/bures/mailtrain/commit/4f52b571c94a05f4a2ee75505b418d1fb96b885e) for progress.

**Comment by bures** [comment] 2017-06-01 11:41
@jdfx, how do you envision one would work with the template tags? Some use-case or a bit more details. Thanks.

**Comment by jdfx** [comment] 2017-06-01 22:13
> The DB index is the actual listID. The number shown in the UI is misleading.

@witzig The issue is that the API end-point for adding a subscriber to a list (/subscribe/{listId}) wants the cid of the list not the DB id. Currently the only way to get the cid of the list (i think) is from the UI. Either the list end-point needs to accept the DB index id or the get /lists I added needs to return the cid for use.

> how do you envision one would work with the template tags? Some use-case or a bit more details. Thanks.

@bures The idea of the template tags is to avoid relying on naming conventions of the template title when getting the correct template. My particular use-case is setting up numerous campaigns programatically for different publication subscriptions.

For example, I could setup templates with the following tags:

- Template 1 'Aviation Weekly', tags: AV, Welcome letter
- Template 2 'Aviation Weekly', tags: AV, Subscription reminder

I am then writing a seperate application that will call my other API and create the necessary campaigns for each publication. My seperate application knows that the module code is AV and that it needs to setup a welcome letter campaign; so when the script runs, it will look for a template with the tags AV and Welcome letter, if it can't find one then it will throw me an error and say go and create it.

That was the general idea anyway.

You're ORM/React re-work looks very promising; do you have a rough ETA?

**Comment by witzig** [comment] 2017-06-02 18:30
@jdfx, thanks. Now I understand.

> or the get /lists I added needs to return the cid for use.

Seems like the obvious call for me. :-)

**Comment by jdfx** [comment] 2017-06-03 08:10
agreed, I'll add that in :)

**Comment by bures** [comment] 2017-06-04 22:18
> @bures The idea of the template tags is to avoid relying on naming conventions of the template title when getting the correct template. My particular use-case is setting up numerous campaigns programatically for different publication subscriptions.

I see. Something like the key/value pairs one can assign to pretty much anything on AWS. Right?

It may make sense. I would suggest that for the time being, we give this option to read and manage tags only through the API. It will be easier to implement and we don't have to clutter the UI with technical things.

> You're ORM/React re-work looks very promising; do you have a rough ETA?

Happy that you like it. The ETA is hard to determine. The intention is to move to React and Knex rather gradually (starting with the new features and then gradually refactoring the existing one). I've been working on it this weekend, however my weekdays a a bit full with my job duties. 

BTW, with the introduction of React, we start moving to REST-based endpoints, which are pretty much like API. Only they protect the access via requiring the user session and CSFR token (instead of requiring the API access token). I'm wondering, how much similarity we have here with the API endpoints. Any chance to see the progress of your updates in this issue (#181)?

**Comment by jdfx** [comment] 2017-08-18 12:11
@bures I am just getting back to this project after being pulled onto something else.

I have a fork of the main repo over at https://github.com/jdfx/mailtrain I will push another commit soon when I am done with the next section but so far I have added Swagger and completed a number of the tasks you see above.

I am currently working on the template tags.

Can I ask how you are getting on with your React stuff etc, I fear my code may be quite far out of sync with the main repo by now.

**Comment by bures** [comment] 2017-08-20 08:47
Perfect.

The React stuff is roughly in one third. Reports, user management, namespace management and login are more or less finished. I hope to complete "Lists" tab in a few days. Templates, Campaigns, Automation are still to be done.

It's actually quite a lot because it also includes refactoring models to use async/await to work with DB and creating a new set of REST endpoint for the React client.

I'm developing the client in my own fork of the repo. Just merge it against the master and make a pull request to get it to Mailtrain's master. We'll then see what it looks like and how it relates to what I have done so far. Thanks.

**Comment by gkrol-zermelo** [comment] 2017-11-08 11:29
I've added API support to get all subscribers for a list. See the pull request https://github.com/Mailtrain-org/mailtrain/pull/348 and the branch at https://github.com/zermelo-software/mailtrain/tree/api_extensions

**Comment by afilp** [comment] 2017-11-13 13:30
@bures Is there a branch to review and contribute to the React code? Also, can you please add the new API enhancements as I also need them for dynamically creating lists, etc? Thanks a lot!

**Comment by renewooller** [comment] 2020-05-15 05:30
I looked into jdfx and bures's branches and they seem to be based on v1, so I'll go ahead and fork off v2 and add the APIs.

**Comment by forgeOneHQ** [comment] 2021-08-29 22:58
@renewooller you can fork it and create a new pull request on this. I close this issue since it is pretty old to get an overview over the latest topics.

**Closed by forgeOneHQ** 2021-08-29 22:58 UTC

**Comment by macpijan** [comment] 2021-09-01 08:15
I can see there was some effort here in terms of API improvements, but it's not clear to me what was merged, and what still needs work (make something can be picked up, refreshed and contributed)?

My goal would be similar as stated here: https://github.com/Mailtrain-org/mailtrain/issues/181#issuecomment-304724081 - to create and send a campaign (based on either a plaintext or HTML file) via API.
