### ISSUE TITLE
List deleted, now no new mails can be send

### ISSUE THREAD

**Issue by lightonflux** [Mailtrain-org/mailtrain#433] opened 2018-05-29 11:59 UTC
Hello.

I deleted a list that was still used by a RSS campaign. So i delete the campaign afterwards. 

Sadly, since the list was deleted MT does not send emails. All new entries (in all other campaigns) that were added to a feed after the deleting are stuck at the "sending" stage.

Any idea why that happens?  Why does it lookup list 5, if no campaign exists that uses it? Why are all others campaigns stuck?

And any suggestion how to get MT sending again. Any MySQL entries i can purge?

Log (stdout/stderr):

```
ERR! Mail Error: ER_NO_SUCH_TABLE: Table 'mailtrain.subscription__5' doesn't exist
ERR! Mail     at Query.Sequence._packetToError (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
ERR! Mail     at Query.ErrorPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
ERR! Mail     at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:279:23)
ERR! Mail     at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)
ERR! Mail     at Protocol.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:39:16)
ERR! Mail     at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:103:28)
ERR! Mail     at emitOne (events.js:116:13)
ERR! Mail     at Socket.emit (events.js:211:7)
ERR! Mail     at addChunk (_stream_readable.js:263:12)
ERR! Mail     at readableAddChunk (_stream_readable.js:250:11)
ERR! Mail     --------------------
ERR! Mail     at Protocol._enqueue (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:145:48)
ERR! Mail     at PoolConnection.query (/opt/mailtrain/node_modules/mysql/lib/Connection.js:208:25)
ERR! Mail     at db.getConnection (/opt/mailtrain/services/sender.js:202:44)
ERR! Mail     at Ping.onOperationComplete [as _callback] (/opt/mailtrain/node_modules/mysql/lib/Pool.js:110:5)
ERR! Mail     at Ping.Sequence.end (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
ERR! Mail     at Ping.Sequence.OkPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
ERR! Mail     at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:279:23)
ERR! Mail     at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)
ERR! Mail     at Protocol.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:39:16)
ERR! Mail     at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:103:28)
```

**Comment by Hocuri** [comment] 2021-08-28 18:19
We just had the same issue. However, this is a duplicate of https://github.com/Mailtrain-org/mailtrain/issues/378, so you should probably close this issue here and, if you think some info is missing there, add it there.

Update: Also, we found a solution: https://github.com/Mailtrain-org/mailtrain/issues/378#issuecomment-907672844

**Comment by forgeOneHQ** [comment] 2021-08-29 21:35
Please install v2, I close this issue now. 

V1 is EOL.

**Closed by forgeOneHQ** 2021-08-29 21:35 UTC
