### ISSUE TITLE
V2: Performance issues

### ISSUE THREAD

**Issue by talheim-it** [Mailtrain-org/mailtrain#879] opened 2020-04-14 08:31 UTC
I have some weird situation I did not get behind it yet.
Version: Build 2019-12-07-1409

1. When I create a new campaign and use the data from an existing campaign, the mosaico editor is not showing up all content, I don't see all blocks. Also when I try to open an existing one. Seems like I have to switch the browser (Primarly I use Brave (Chromium based), I have to switch to Firefox).
![image](https://user-images.githubusercontent.com/15981620/79203033-be0dcd80-7e3a-11ea-96b3-216b631ba2ab.png)

Also when I switch back from the "content" page to statistics or any other page, sometimes it shows up that the changes were not saved. Maybe it has to do with the DB but I am not sure.

I have to wait or restart mailtrain then which is a strange behaviour, especially when campaigns sent. Waiting means around 30 seconds to 1 minute and more till it works again.

Is there a log file where the mailtrain application is logging all error information in?

**Comment by taenzerme** [comment] 2020-05-27 11:52
I have the same problem. We noticed this happens when running behind a proxy (we tested Apache and Traefik). Images from the sandbox are not loaded and Mailtrain "hangs" for 30 seconds or longer then.

@bures Any idea why Mailtrain does have problems behind a proxy? This is a showstopper at the moment. I tried a lot of things already and don't see anything wrong with the server implementation right now. Any help or ideas really appreciated!

**Comment by bures** [comment] 2020-05-27 11:59
I'm afraid I have no idea. Doesn't happen to me. I'll be happy to check it out, but first I have to be able to replicate it.

**Comment by taenzerme** [comment] 2020-05-27 11:59
I could offer you access to our demo installation behind an Apache2 proxy?

**Comment by talheim-it** [comment] 2020-05-27 12:04
@bures it primarly happends after sending.

I use it behind an NGINX proxy. Other applications like rocket.chat I use don't have it.

So it seems like when you send the campaign it takes. Or when I copy an existing one. I just have to wait a bit till it is loading correctly.

I would like to check log files but I don't see any.

**Comment by taenzerme** [comment] 2020-05-27 12:19
It happens here when accessing sites with the editors embedded from the sandbox.

**Comment by bures** [comment] 2020-05-27 18:57
@taenzerme If you have a server I could get ssh access to, I can try to check if I see anything suspicious. In any case, I would need your assistance in replicating the problem. Unless I can reliable replicate it, no way I can debug it. Thanks.

**Comment by taenzerme** [comment] 2020-05-27 19:08
@bures Working on it. Have to set up a clean Debian VM w/ Apache proxy and Mailtrain. Right now Mailtrain is running in our Docker swarm and the Apache proxy is a central one I can't give access to.

**Comment by bures** [comment] 2020-05-27 19:20
@taenzerme Perfect. Thanks. Let me know then on my email. I'll send you my public ssh key and we can agree on some time when you are available to help me replicate the issue.

**Comment by taenzerme** [comment] 2020-05-27 21:40
@bures Server is ready. I've sent you an email.

This time it's a standard Debian 10, nginx as a reverse proxy and Mailtrain running with docker-compose. Env variables are set correctly and everything else is working fine.

I can replicate the problem when opening the campain content editor. Either it's stuck loading instantly or after some time. When trying to reload it's still stuck for 30-40 seconds.

When its blocked this is logged to the console:

`mailtrain_1  | info HTTP GET /ad0a622bc772abb5efc2dbb3dd781e6d18136ad73947e12e/mosaico/templates/1/edres/tripleArticleBlock.png - - ms - -
mailtrain_1  | info HTTP GET /ad0a622bc772abb5efc2dbb3dd781e6d18136ad73947e12e/mosaico/templates/1/edres/socialBlock.png - - ms - -
mailtrain_1  | info HTTP GET /ad0a622bc772abb5efc2dbb3dd781e6d18136ad73947e12e/mosaico/templates/1/edres/doubleArticleBlock.png - - ms - -
mailtrain_1  | info HTTP GET /ad0a622bc772abb5efc2dbb3dd781e6d18136ad73947e12e/mosaico/templates/1/edres/tripleImageBlock.png - - ms - -
mailtrain_1  | info HTTP GET /ad0a622bc772abb5efc2dbb3dd781e6d18136ad73947e12e/mosaico/templates/1/edres/textBlock.png - - ms - -
mailtrain_1  | info HTTP GET /ad0a622bc772abb5efc2dbb3dd781e6d18136ad73947e12e/mosaico/templates/1/edres/imageBlock.png - - ms - -
mailtrain_1  | info HTTP GET /ad0a622bc772abb5efc2dbb3dd781e6d18136ad73947e12e/mosaico/templates/1/edres/sideArticleBlock.png - - ms - -
mailtrain_1  | info HTTP GET /ad0a622bc772abb5efc2dbb3dd781e6d18136ad73947e12e/mosaico/templates/1/edres/spacerBlock.png - - ms - -
mailtrain_1  | info HTTP GET /ad0a622bc772abb5efc2dbb3dd781e6d18136ad73947e12e/mosaico/templates/1/edres/doubleImageBlock.png - - ms - -
mailtrain_1  | info HTTP GET /ad0a622bc772abb5efc2dbb3dd781e6d18136ad73947e12e/mosaico/templates/1/edres/singleArticleBlock.png - - ms - -
mailtrain_1  | info HTTP GET /ad0a622bc772abb5efc2dbb3dd781e6d18136ad73947e12e/mosaico/templates/1/edres/titleBlock.png - - ms - -
mailtrain_1  | info HTTP GET /ad0a622bc772abb5efc2dbb3dd781e6d18136ad73947e12e/mosaico/templates/1/edres/buttonBlock.png - - ms - -
mailtrain_1  | info HTTP GET /ad0a622bc772abb5efc2dbb3dd781e6d18136ad73947e12e/mosaico/templates/1/edres/hrBlock.png - - ms - -
mailtrain_1  | info HTTP GET /static/mosaico/rs/img/mosaico32.png 304 60094.268 ms - -`

The same when it is not blocked:

`mailtrain_1  | info HTTP GET /597ae5bf009e618776d3045a4a487b84d8c93893003e575e/mosaico/templates/1/edres/logoBlock.png 200 53.869 ms - 5232
mailtrain_1  | info HTTP GET /597ae5bf009e618776d3045a4a487b84d8c93893003e575e/mosaico/templates/1/edres/textBlock.png 200 83.954 ms - 9219
mailtrain_1  | info HTTP GET /597ae5bf009e618776d3045a4a487b84d8c93893003e575e/mosaico/templates/1/edres/sideArticleBlock.png 200 83.992 ms - 9710
mailtrain_1  | info HTTP GET /597ae5bf009e618776d3045a4a487b84d8c93893003e575e/mosaico/templates/1/edres/singleArticleBlock.png 200 101.676 ms - 16143
mailtrain_1  | info HTTP GET /597ae5bf009e618776d3045a4a487b84d8c93893003e575e/mosaico/templates/1/edres/doubleArticleBlock.png 200 352.854 ms - 8498
mailtrain_1  | info HTTP GET /597ae5bf009e618776d3045a4a487b84d8c93893003e575e/mosaico/templates/1/edres/tripleArticleBlock.png 200 373.214 ms - 7698
mailtrain_1  | info HTTP GET /597ae5bf009e618776d3045a4a487b84d8c93893003e575e/mosaico/templates/1/edres/titleBlock.png 200 750.640 ms - 1503
mailtrain_1  | info HTTP GET /597ae5bf009e618776d3045a4a487b84d8c93893003e575e/mosaico/templates/1/edres/buttonBlock.png 200 905.550 ms - 1045
mailtrain_1  | info HTTP GET /597ae5bf009e618776d3045a4a487b84d8c93893003e575e/mosaico/templates/1/edres/hrBlock.png 200 905.618 ms - 198
mailtrain_1  | info HTTP GET /597ae5bf009e618776d3045a4a487b84d8c93893003e575e/mosaico/templates/1/edres/doubleImageBlock.png 200 901.377 ms - 9001
mailtrain_1  | info HTTP GET /static/mosaico/rs/img/mosaico32.png 304 866.316 ms - -
mailtrain_1  | info HTTP GET /597ae5bf009e618776d3045a4a487b84d8c93893003e575e/mosaico/templates/1/edres/tripleImageBlock.png 200 899.350 ms - 4375
mailtrain_1  | info HTTP GET /597ae5bf009e618776d3045a4a487b84d8c93893003e575e/mosaico/templates/1/edres/imageBlock.png 200 902.819 ms - 9985
mailtrain_1  | info HTTP GET /597ae5bf009e618776d3045a4a487b84d8c93893003e575e/mosaico/templates/1/edres/spacerBlock.png 200 898.338 ms - 153
mailtrain_1  | info HTTP GET /597ae5bf009e618776d3045a4a487b84d8c93893003e575e/mosaico/templates/1/edres/socialBlock.png 200 895.696 ms - 2749
mailtrain_1  | info HTTP GET /anonymous/static/mosaico/rs/skins/gray-flat/skin.min.css 304 1.728 ms - -
mailtrain_1  | info HTTP GET /anonymous/static/mosaico/rs/skins/gray-flat/content.inline.min.css 304 1.663 ms - -
mailtrain_1  | info HTTP PUT /rest/restricted-access-token 200 15.779 ms - -
mailtrain_1  | info HTTP PUT /rest/restricted-access-token 200 94.522 ms - -
mailtrain_1  | info HTTP PUT /rest/restricted-access-token 200 12.693 ms - -
mailtrain_1  | info HTTP PUT /rest/restricted-access-token 200 466.948 ms - -`

**Comment by taenzerme** [comment] 2020-05-27 21:42
Btw, this appears to be a duplicate of https://github.com/Mailtrain-org/mailtrain/issues/821

**Comment by bures** [comment] 2020-05-27 23:06
Please, try it out now.

**Comment by taenzerme** [comment] 2020-05-27 23:09
It's works 🎉

**Comment by bures** [comment] 2020-05-27 23:10
Great! Thanks a lot.

**Comment by taenzerme** [comment] 2020-05-27 23:16
Thanks to you! I will test this with another Traefik setup tomorrow, but it's looking good so far. No more problems right now.

**Comment by talheim-it** [comment] 2020-05-28 17:44
Seems to work with nginx. Much better. Just images loading is taking a bit if you have a few but overall, no issues with loading the editor.

Thank you @bures

**Comment by bures** [comment] 2020-05-28 17:54
Happy to hear. I'm closing this issue. If the bug appears again, please reopen it.

**Closed by bures** 2020-05-28 17:54 UTC
