### ISSUE TITLE
Mailtrain V2 websites not available after fresh installation

### ISSUE THREAD

**Issue by H3avy6unner** [Mailtrain-org/mailtrain#1054] opened 2021-05-01 12:35 UTC
Hello guys,

I've tried to install mailtrain v2 local for ubuntu 18.04. I followed the installation guide on the mainpage with a complete fresh ubuntu 18.04 server. After some issues with `npm`, which could solved by using `sudo su-` to start the `install-ubuntu1804-local.sh`, the installation could finished successfully.

When I try to reach the webinterface on port 3000, I only get a blank page. Mailtrain.service shows `info HTTP GET / 200` and nothing further happens. If I try to reach 3003 or 3004 I get an an `Cannot GET /`

I tried to reach the interfaces by IP address and localhost. I already tried to change de URL_BASE but this does not to work either. In the end I tried to use docker but running into the same issues.

What I am doing wrong here?

**Comment by tfmm** [comment] 2021-05-02 19:26
Having the same issue, tried curling by IP/Port as well as by the URL in URL-base.  The trusted base works correctly, just not the public. 

In my instance I have tried with Mailtrain behind an Amazon Application Load Balancer and just behind raw NGINX.

**Comment by bures** [comment] 2021-05-26 05:07
My guess is that the URL bases in your config are messed up. But of course, I would need some logs to diagnose the problems. It least the output of curl and details of your IPs and url-bases.

**Comment by Kraftwurm** [comment] 2021-06-02 14:57
Ubuntu 16.04 was not working for me as well. Also CentOS 7 was not working. BUT Ubuntu 20.04 works fine for me!
(without any changes and WITHOUT apt upgrade)

**Comment by bures** [comment] 2021-06-02 14:59
Good. I guess Ubuntu 16.04 is not relevant any more. CentOS 7 surprises me, but anyway, it has been long replaced by CentOS 8. So I'd suggest to close this issue.

**Comment by Kraftwurm** [comment] 2021-06-02 21:14
I was trying Centos 7 specifically and Ubuntu 18.04 because that's what is
called for in the readme of the github project. Maybe you should fix that?

I can confirm that it works for me with Ubuntu 20.04 WITHOUT apt upgrade !

The only problem I had was the UPLOADS of images not working. But your tip
in another issue (chown mailtrain:mailtrain /opt/mailtrain I think) helped.
Maybe you should add/fix that too because it almost steered me away from
the project.

Thanks for your great work!

**Closed as completed** 2021-08-29 23:38 UTC

**Comment by phtmgt** [comment] 2022-10-13 09:39
Same here, docker. 404s on sbox and lists, empty page on trusted.

EDIT: I was able to get trusted to work. Still getting the 404s on the other 2, though.
